version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      PORT: 4000
      NODE_ENV: production
      MONGO_URL: mongodb+srv://z5rk_user:dbLqJeXjtTje5ZNS@cluster0.id1nw.mongodb.net/z5rk?retryWrites=true&w=majority
      NFT_API_APP_ID: 73LYGy6RNPc4lXr9BSb9RBbChLIdjFHeJ6PKMbbn
      NFT_API_MORALIS_SECRET: mCNSR8qnDZ8cnKjcbpKfjSiy7sQGHgM8NhFjqfrs1tXY1j6GzFsWjBm9VrksJsNs
      NFT_API_SERVER_URL: https://8reqdyiiexsd.usemoralis.com:2053/server
      STRIPE_PRIVATE_KEY: sk_test_51IafPeLZpePNw5xWA9kL6xSE7uKRA8W0MQ0y0NK2qIZH0ee59jE8WJAbzDF5n2r0SXJKZRjkWQBAr9pE5GApSN9300uxMz0Hm4
      CLIENT_URL: https://client_url.io
    ports:
      - 4000:4000
    depends_on:
      - mongo_db
    links:
      - mongo_db
    volumes:
      - .:/usr/src/app
  mongo_db:
    image: mongo:latest
    ports:
      - 27016:27016
    volumes:
      - data:/data/db
volumes:
  data:
